
version: 0.2
phases:
 install:
   commands:
     - npm i -g gatsby
 pre_build:
   commands:
     - npm i
 build:
   commands:
     - npm run build
 post_build:
   commands:
     - aws s3 sync --acl "public-read" --delete ./public "s3://sarabethbelon.com"
     - aws cloudfront create-invalidation --distribution-id E1ZD69ENH99ZEM --paths /*